apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: http
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
