apiVersion: v1
data:
  password: HFGHJGfkhdkllhfkushkuefskbbxnjdn==
  user: jfbkeb
kind: Secret
metadata:
  name: writeo-database-secret
  namespace: demo
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: writeo-database-init-sql
  namespace: demo
data:
  init.sql: |-
    CREATE DATABASE IF NOT EXISTS `auser`;
    CREATE DATABASE IF NOT EXISTS `aarticle`;
---
apiVersion: kubedb.com/v1alpha2
kind: MySQL
metadata:
  name: writeo-database
  namespace: demo
spec:
  authSecret:
    name: writeo-database-secret
  version: "8.0.3-v3"
  storageType: Durable
  storage:
    storageClassName: standard
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  podTemplate:
    spec:
      args:
        - --default-authentication-plugin=mysql_native_password
      env:
        - name: MYSQL_ROOT_HOST
          value: "%"
  terminationPolicy: Delete
  init:
    script:
      configMap:
        name: writeo-database-init-sql
