name: Nest CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: ./auth-api
    - run: npm run build
      working-directory: ./auth-api
    - run: npm test
      working-directory: ./auth-api
    - run: npm install
      working-directory: ./article-api
    - run: npm run build
      working-directory: ./article-api
    - run: npm test
      working-directory: ./article-api
    - run: npm install
      working-directory: ./rating-api
    - run: npm run build
      working-directory: ./rating-api
    - run: npm test
      working-directory: ./rating-api
