replicaCount: 1

image:
  repository: ""
  pullPolicy: ""
  tag: ""

containerPort: 3000
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
checks:
  livenessProbe:
    enabled: false
    path: /
    port: http
    initialDelaySeconds: 5
    periodSeconds: 5
  readinessProbe:
    enabled: false
    path: /
    port: http
    initialDelaySeconds: 5
    periodSeconds: 5

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingres.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    memory: "512Mi"
    cpu: "500m"
  requests:
    memory: "256Mi"
    cpu: "200m"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50

nodeSelector: {}

tolerations: []

affinity: {}

database:
  enabled: false
  name: ""
  storage: 1G
  storageClassName: standard
  user: ""
  password: ""
  dbName: ""
